name: Cancel CI on PR Close

on:
  pull_request:
    types:
      - closed

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow runs
        uses: actions/github-script@v6
        with:
          script: |
            const runs = await github.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: context.payload.pull_request.head.ref,
              event: 'pull_request',
              status: 'in_progress',
            });

            for (const run of runs.data.workflow_runs) {
              await github.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id,
              });
            }
