name: Cancel CI on PR Close

on:
  pull_request:
    types:
      - closed

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: node.yml
